### ISSUE TITLE
run deepimpute on the commandline

### ISSUE THREAD

**Issue by Zhangxf-ccnu** [lanagarmire/deepimpute#2]
Hi,

I am trying to run deepimpute under python 3.5 on the commandl ine. I have the following issue:

Traceback (most recent call last):
  File "deepImpute.py", line 65, in <module>
    imputed.to_csv(args.outputFile)
AttributeError: 'Namespace' object has no attribute 'outputFile'

When I replaced "imputed.to_csv(args.outputFile)" with "imputed.to_csv(args.o)", the code can be run without error. Can you please check it.

In addition, how can I set the **NN_params on the commandline. Can you please update your code so that the **NN_params can be set by users. For example, we can set the network paramters in the DCA package (https://github.com/theislab/dca)

help would be appreciated.

Thanks,

xiaofei

**Comment by Puumanamana** [comment]
Hi Xiaofei,

Thank you for trying DeepImpute and sorry for the inconvenience. You were right about the output, it should be working fine now.

As you requested, I changed the command line so that you're able to tune the network hyperparameters directly. You should be able to see how to do it with python deepimpute.py -h or in the README.

Let us know if you have any other issue or suggestion.

Regards,

Cedric

**Comment by Zhangxf-ccnu** [comment]
Hi Cedric,

       Your update works. Thank you for the quick reply.

Regards,

xiaofei
