### ISSUE TITLE
Inquiry about computation time

### ISSUE THREAD

**Issue by kexinhuang12345** [lanagarmire/deepimpute#23]
Hi,

Thanks for the great work. In the paper, it reports around 1 minute for around 3000 cells for mouse1M. How large is the gene set size? Because for me, I am running a dataset of 3000 cells and 30000 genes. But deepimpute takes many hours using the default ipynb example functions. Is this expected? Thanks!

**Comment by lanagarmire** [comment]
Kuxin,
In our demo, we have been filtering genes upfront to be about 2000 genes.
You will need to filter the genes by mean/variance ration first.

Cedric, can you give him more details/help?

Thanks
Lana

**Comment by Puumanamana** [comment]
Hi,

The filtering step is included in deepImpute. It discards genes with a VMR lower than a threshold of 0.5 (default value). It usually discards many genes that do not carry much information and we end up usually with less than 10k genes. Depending on your dataset (I noticed it more for Fluidigm 10X datasets), you tend to keep more genes. 

Because DeepImpute builds all of the sub-networks simultaneously, having more genes will require more memory to fit everything in memory. If you don't, then your computer will start using swap memory and things will start to become very slow. My advice would be to either increase you memory resources (by running the imputation on a HPC for instance) or by reducing the number of genes to impute. You can do that by choosing the number manually with the --limit argument or by increasing the minVMR to 1 for instance.

Cédric

**Comment by kexinhuang12345** [comment]
Hi, 

Thanks, I will try it out. Closing for now.
